version: '2'
services:
    ms-security:
        container_name: ms-security
        build: ./ms-security
        ports:
            - '3001:3000'
        volumes: 
            - './ms-security:/usr/src/app'